### ISSUE TITLE
Slight incline when not using the available sunpy maps

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#11]
While loading a recent map, `AIA20210601_1300_0193.fits`, the map seems to be inclined slightly towards the y axis. 
Is this intended behaviour?
If yes, I think we should set the solar axis relative to the map itself so that the axis is pointing exactly upwards and not at an angle
![image](https://user-images.githubusercontent.com/50923538/121407698-37d91280-c97d-11eb-9f6b-cbcddb893dba.png)

**Comment by dstansby** [comment]
This is expected, as the Earth's orbit around the Sun is tilted by ~7 degrees relative to the solar north pole. If you plot a map observed 6 months earlier, the tilt should be in the other direction, which would be a good check that this is the reason for the tilt.

**Comment by jeffreypaul15** [comment]
Ah okay, the other map is tilted in the other direction, shouldn't we keep the solar axis relative to the map then?

**Comment by dstansby** [comment]
No, the solar axis is fixed, but the maps just change their tilt depending on the angle that the Earth is observing the Sun.

**Comment by jeffreypaul15** [comment]
Ah understood, my apologies.
