### ISSUE TITLE
Readthedocs not displaying the examples

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-pyvista#111]
### Describe the bug

RTD no longer displays the example files and we need to track that down.

**Comment by J0SAL** [comment]
Hey @nabobalis, I am new to open source and would love to contribute to this issue. Could you please explain the issue in more detail and the things I need to learn before I start working on it?

**Comment by nabobalis** [comment]
Hi @J0SAL, I am not really sure this is the best problem to start with. I can't stop you obviously, but I will add more detail:

We build the documentation for this project on a system called readthedocs (RTD), https://docs.sunpy.org/projects/sunkit-pyvista/en/latest/

We have three examples: https://docs.sunpy.org/projects/sunkit-pyvista/en/latest/examples/index.html.

At some point in the past, we worked out how to make them render the plot at the end on RTD. This was a combination of some scripting: https://raw.githubusercontent.com/sunpy/sunkit-pyvista/main/docs/examples/setup.py and running jupyter-execute on RTD. They would look like: https://docs.pyvista.org/ where you can manipulate the examples. 

This has now broken and I don't recall when and I don't know why or how to begin working out where to start.
