### ISSUE TITLE
Combine meshes from plot_field_lines() into a single StructuredGrid?

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#21]
`plot_field_lines()` draws field lines from Pfsspy where we loop through the `field_lines` and add them as separate meshes,
would it be better to combine them into a single `StructuredGrid()` or create `MultiBlock()` and append to this grid?
Of course, there is the color issue that persists here as well, if we combine them into a single `grid` we'd have to figure out a way to plot the meshes with the right color.
A `MultiBlock()` would be better because we could separate them and define `field_arrays` (if we're worrying about colors) as well.

**Comment by dstansby** [comment]
Are there advantages to using a `StructuredGrid` or `MultiBlock`?

**Comment by jeffreypaul15** [comment]
> Are there advantages to using a `StructuredGrid` or `MultiBlock`?

Well, as of now we don't have any access to the meshes once we add them to `plotter` using `add_mesh`.
When we save the meshes, we combine them to a `MultiBlock`.
If we want to change a previously existing mesh, we can't do that, if we store all of them in a `MultiBlock` with the field lines being part of a `MultiBlock` as well, we can access each mesh and it's data individually.

This would come in handy if we're worried about saving and colors and stuff

**Comment by jeffreypaul15** [comment]
Closed via #24 and #37
