### ISSUE TITLE
Difference in images when running tests

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#40]
The figure tests from #39 uncovered that the same map plotted locally and when run through the tox environment gives different images with the same code.
Map plotted when testing through tox :
![image](https://user-images.githubusercontent.com/50923538/125390377-6bfe8380-e3c0-11eb-9113-0177f970e826.png)

The same map plotted locally : 
![image](https://user-images.githubusercontent.com/50923538/125390583-c0096800-e3c0-11eb-8cbc-92237ae5ea78.png)

**Comment by dstansby** [comment]
That doesn't look great! What's the script (or test function) you're using to make these plots?

**Comment by jeffreypaul15** [comment]
I'm just using the base plotter and passing in the map

**Comment by jeffreypaul15** [comment]
The map seems to be inside out with its data, I'm not sure why that's happening

**Comment by dstansby** [comment]
I've just run the tests in #39 using both pytest and tox, and I get passing tests both ways, so I'm not sure where the two images above are from? Either way, the currently test failure on #39 is for `draw_quadrangle`, so I think we can close this issue as not an issue?

**Comment by dstansby** [comment]
To sum up, @jeffreypaul15 discovered this was a difference between sunpy 3.0.0 and 3.0.1, and I've managed to track the difference down to https://github.com/sunpy/sunpy/pull/5420. This was a bugfix, so we should add a `sunpy!=3.0.0` pin to our requirements, which I will do now.
