### ISSUE TITLE
Plotting single coordinate might be faulty?

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#47]
Based on #44
```py
pixel_pos = np.argwhere(m.data == m.data.max()) * u.pixel
hpc_max = m.pixel_to_world(pixel_pos[:, 1], pixel_pos[:, 0])
```

`hpc_max` when passed to `plot_coordinates` produces an array of shape (1, 3) which is a single point but gets plotted as a spline.
We would have to pass `hpc_max[0]` to get the corresponding point to be plotted as a sphere, do we want this to be the case,
or should we check if the coordinates consists of a single point instead of using `ndim`?

**Comment by dstansby** [comment]
I think this line:
https://github.com/sunpy/sunkit-pyvista/blob/5d2301fddadcff283ca3bd4a4c7b8b1cfcfceaee/sunkit_pyvista/plotter.py#L210

can be changed to `if points.ndim == 1 or (points.ndim == 2 and points.shape[0] == 1):` to fix this?

**Comment by jeffreypaul15** [comment]
> I think this line:
> 
> https://github.com/sunpy/sunkit-pyvista/blob/5d2301fddadcff283ca3bd4a4c7b8b1cfcfceaee/sunkit_pyvista/plotter.py#L210
> 
> can be changed to
> 
> ```python
> if points.ndim == 1 or (points.ndim == 2 and points.shape[0] == 1):
> ```
> 
> to fix this?

Sure, shall I make a PR for this?

**Comment by dstansby** [comment]
👍  - would be good to add a test too
