### ISSUE TITLE
Quadrangle mesh is extremely thin

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#49]
When plotting a quadrangle with default thickness, we get
![image](https://user-images.githubusercontent.com/50923538/126080454-3c35e5f7-2cc0-4b4f-9eff-1a9b0c813144.png)

On increasing line_width to 10 or more, the corners of the quadrangle aren't positioned properly.
![image](https://user-images.githubusercontent.com/50923538/126080479-4de17e49-c1b7-4a9e-b7fc-f32c3b9e542c.png)

The quadrangle mesh lies on the same coordinate as the map mesh does, so it has better visibility when look at from behind (default thickness):
![image](https://user-images.githubusercontent.com/50923538/126080512-58bdc3a1-8774-4e07-b79e-a4dc94748247.png)

Would it be better to offset the quadrangle coordinates by a small percent? So that they would be more visible in front rather than the back?

**Comment by nabobalis** [comment]
Offset in Z?

**Comment by jeffreypaul15** [comment]
> Offset in Z?

In all axes, just increasing the current value by a certain percentage?

**Comment by dstansby** [comment]
I think we should just increase the radius of the points a little bit, so they're plotted at 1.01 solar radii instead of 1 solar radii.

**Comment by dstansby** [comment]
This way they should appear above the Map mesh

**Comment by jeffreypaul15** [comment]
Yep that makes sense, I'll make a PR for this

**Comment by jeffreypaul15** [comment]
Closed via #52
