### ISSUE TITLE
Allow users to specify custom function to color field lines

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-pyvista#50]
Currently the function we use to set the field line color is fixed. It would be good to leave this as the default, but allow the user to specify a function that takes a single `FieldLine` object and returns a color. Writing this as a note in a hurry, but I can elaborate on this (or open a PR myself) later today.

**Comment by dstansby** [comment]
To be a bit clearer, the API I have in mind is:

```python
plot_field_lines(field_lines, color_func, **kwargs)
```

where `color_func` is a user supplied function that has the signature
```python
color_func(field_line: pfsspy.fieldline.FieldLine) -> str:
    ...
    return color_str
```
We can then replace this line:
https://github.com/sunpy/sunkit-pyvista/blob/4338edbfa3642adc060f89acc3f4bfb9baa37e0b/sunkit_pyvista/plotter.py#L372
with the user supplied function to color the field lines, but still keep the above line as the default option.

As an example function, if I wanted to color by the magnetic field expansion factor I could pass a function that was:

```python
def my_fline_color_func(fline):
    norm = mcolor.LogNorm(vmin=1, vmax=1000)
    cmap = plt.get_cmap('viridis')
    return cmap(norm(np.abs(fline.expansion_factor))
```

Does this make sense @jeffreypaul15 ?

**Comment by jeffreypaul15** [comment]
I'm sorry @dstansby I don't quite follow how the `my_fline_color_func` works as it doesn't return a string?

**Comment by dstansby** [comment]
Ah yes, the function should be allowed to return any colour that pyvista allows, which in the [documentation for `add_mesh`](https://docs.pyvista.org/plotting/plotting.html#pyvista.BasePlotter.add_mesh) says
> Either a string, RGB list, or hex color string.
