### ISSUE TITLE
Default colour of Spline is based on value

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#60]
In Pyvista, the default value for color that Spline takes is based on it's arc length values (created when a spline is made from the existing points).
Both quadrangle, limb and maybe grid if we implement it would be using Spline, should we settle on a default colour instead of this?
![image](https://user-images.githubusercontent.com/50923538/127676774-21b7be99-61dc-4ffc-89ed-397a2d8a713c.png)

**Comment by dstansby** [comment]
Yes, we definitely should have a default colour - what about white?
