### ISSUE TITLE
Fix doc build

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-pyvista#64]
The doc build is currently failing due to either a warning or error in running the current example. This isn't the end of the world as we can rely on readthedocs for now, but this should be fixed at some point.

**Comment by nabobalis** [comment]
Docs now emit:

```
/home/runner/work/sunkit-pyvista/sunkit-pyvista/.tox/build_docs/lib/python3.9/site-packages/pyvista/jupyter/pv_pythreejs.py:436: UserWarning: Empty or unsupported dataset attached to actor
  warnings.warn('Empty or unsupported dataset attached to actor')
```
I am unsure what example emits this.
