### ISSUE TITLE
Save colormaps as 'cmap' in field arrays instead of 'color'

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunkit-pyvista#76]
The load method should also be updated for this change accordingly as we have to check for the existence of a `cmap` in the field array.
@dstansby Should we warn the user if a color value as well as a cmap is passed to add_mesh? In pyvista, the color argument takes preference.

**Comment by dstansby** [comment]
I don't think we should warn, I think we should pass them both through to `pyvista` that can decide what to do with them.

**Comment by jeffreypaul15** [comment]
> I don't think we should warn, I think we should pass them both through to `pyvista` that can decide what to do with them.

Alright, I'll make this change in the new PR
