### ISSUE TITLE
Running example doesn't produce a plot

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-pyvista#9]
I just tried running:
```bash
python examples/skip_plot_map_in_3d.py 
```

It all worked fine, but it didn't show a plot at the end and just stopped. Is there a testing/docs reason we can't show the plot at the end of examples? Ideally I think we want it set up so when a user runs the example locally they get the plots.

**Comment by jeffreypaul15** [comment]
> It all worked fine, but it didn't show a plot at the end and just stopped. Is there a testing/docs reason we can't show the plot at the end of examples? Ideally I think we want it set up so when a user runs the example locally they get the plots.

The docs have xvfb server enabled with `pv.start_xvfb()`, otherwise RTD produces a segmentation fault.
I've left it in for now, do we comment saying remove this line if run locally?

**Comment by dstansby** [comment]
I think this line might need changing too to remove `off_screen`:
https://github.com/sunpy/sunkit-pyvista/blob/9edbe70133bfc2f2804d4c20287f68749a858bcc/sunkit_pyvista/plotter.py#L32

**Comment by jeffreypaul15** [comment]
> I think this line might need changing too to remove `off_screen`:
> https://github.com/sunpy/sunkit-pyvista/blob/9edbe70133bfc2f2804d4c20287f68749a858bcc/sunkit_pyvista/plotter.py#L32

Off-screen wasn't there originally, I was trying to get the RTD to work and had added it in then

**Comment by dstansby** [comment]
Okay, I've opened https://github.com/pyvista/pyvista/issues/1350 to see if there's a way we can switch this on with RTD, but leave it switched off by default. I think for now it would be good to remove `off_screen=True` so we can at least try the examples out locally?

**Comment by dstansby** [comment]
I think this is fixed now
